export const STOREDETAILS_PAGE = "STOREDETAILS_PAGE";
export const STORETYPE_SELECTED = "STORETYPE_SELECTED";
export const STOREDETAILS_SUBMITTED = "STOREDETAILS_SUBMITTED";
export const STORE_DETAILS = "STORE_DETAILS";